export const COMMON_LABELS = {
  emptyList: "Danh sách trống!",
  close: "Đóng",
  cancel: "Hủy",
  save: "Lưu",
  saving: "Đang lưu...",
  actions: "Thao tác",
  status: "Trạng thái",
  active: "Đang hoạt động",
  inactive: "Ngừng hoạt động",
  activate: "Kích hoạt",
  deactivate: "Ngừng hoạt động",
  search: "Tìm kiếm...",
  confirm: "Xác nhận",
  confirmCannotUndo: "Hành động này không thể hoàn tác.",
  requiredMark: "*",
};

export const CINEMA_ROOM_LABELS = {
  pageTitle: "Quản lý phòng chiếu",
  addRoom: "Thêm phòng",
  columnRoomName: "Tên phòng",
  columnCapacity: "Sức chứa",
  columnFormats: "Định dạng",
  columnStatus: "Trạng thái",
  columnActions: "Thao tác",
  actionDetail: "Chi tiết",
  actionActivate: "Kích hoạt phòng",
  actionDeactivate: "Ngừng hoạt động phòng",
  seatsSuffix: "ghế",

  statusActive: "Đang hoạt động",
  statusInactive: "Ngừng hoạt động",

  filterFormat: "Định dạng",
  filterStatus: "Trạng thái",
  filterAll: "Tất cả",
  clearFilters: "Xóa bộ lọc",
  noRoomMatchesFilter: "Không có phòng chiếu nào khớp với bộ lọc.",
  confirmDeactivateTitle: "Ngừng hoạt động phòng chiếu",
  confirmDeactivateMessage: "Bạn có muốn ngừng hoạt động phòng này không?",
  confirmActivateTitle: "Kích hoạt phòng chiếu",
  confirmActivateMessage: "Bạn có muốn kích hoạt lại phòng này không?",
  hasSchedulesError: "Không thể thực hiện thao tác vì phòng đang có lịch chiếu.",
  editLockedBySchedules: "Phòng đang có suất chiếu — không thể chỉnh sửa thông tin hoặc sơ đồ ghế cho đến khi các suất kết thúc/hủy.",

  createModalTitle: "Tạo phòng chiếu mới",
  fieldRoomName: "Tên phòng",
  roomNamePlaceholder: "Phòng 1",
  fieldRows: "Số hàng",
  fieldColumns: "Số cột",
  fieldTotalCapacity: "Tổng sức chứa",
  fieldFormats: "Định dạng hỗ trợ",
  maxGridError: "Số hàng và số cột tối đa là 10 (tối đa 100 ghế).",
  submitCreate: "Tạo phòng",
  createInactiveHint: "Phòng chiếu mới luôn ở trạng thái Ngừng hoạt động cho đến khi được kích hoạt.",

  formatRequiredError: "Vui lòng chọn ít nhất một định dạng.",

  setupModalTitle: "Thiết lập phòng chiếu",
  roomDetails: "THÔNG TIN PHÒNG",
  capacityLabel: (total, active) => `Sức chứa: ${total} ghế (${active} đang hoạt động)`,
  editInfo: "Chỉnh sửa thông tin",
  seatTools: "CÔNG CỤ GHẾ",
  updateSeatMap: "Cập nhật sơ đồ ghế",
  saveLayout: "Lưu sơ đồ",
  editInfoModalTitle: "Chỉnh sửa thông tin phòng",
  updateSeatMapModalTitle: "Cập nhật sơ đồ ghế",
  recreateWarning: "Thao tác này sẽ tạo lại toàn bộ sơ đồ ghế và đặt lại tất cả ghế về loại Thường.",

  seatTypeNormal: "Ghế thường",
  seatTypeVip: "Ghế VIP",
  seatTypeCouple: "Ghế đôi",
  seatStatusActive: "Đang hoạt động",
  seatStatusInactive: "Ngừng hoạt động",
  seatAisle: "Lối đi",
  seatSelected: "Đang chọn",
  selectRow: "Chọn cả hàng",
  selectColumn: "Chọn cả cột",
  coupleOddCountError: "Không thể tạo ghế đôi vì số ghế được chọn là số lẻ.",
  bookedSeatError: "Không thể thay đổi ghế đã được đặt.",
  coupleHorizontalOnlyError: "Ghế đôi chỉ được ghép ngang: hai ghế phải cùng một hàng và nằm ở hai cột liền kề.",
  coupleDeletedSeatError: "Ghế đã xóa (lối đi) không thể cấu hình làm ghế đôi.",

  resizeDestructiveWarning: (seatCount, coupleCount) =>
    `Sơ đồ hiện tại sẽ bị xóa và tạo lại: ${seatCount} ghế đã thiết lập sẽ trở về loại Thường` +
    (coupleCount > 0 ? `, ${coupleCount} cặp ghế đôi sẽ bị hủy ghép` : "") +
    ". Bạn có chắc chắn muốn tiếp tục?",
  resizeConfirmCheckbox: "Tôi hiểu sơ đồ ghế hiện tại sẽ bị xóa và tạo lại.",
  roomNotFound: "Không tìm thấy phòng chiếu.",
  backToList: "Quay lại danh sách",
};

export const MOVIE_LABELS = {
  pageTitle: "Quản lý phim",
  addMovie: "Thêm phim mới",
  columnPoster: "Poster",
  columnName: "Tên phim",
  columnDuration: "Thời lượng (phút)",
  columnStartDate: "Ngày bắt đầu",
  columnEndDate: "Ngày kết thúc",
  columnGenres: "Thể loại",
  columnFormats: "Định dạng",
  columnStatus: "Trạng thái",
  columnActions: "Thao tác",

  statusUnscheduled: "Chưa lên lịch",
  statusUpcoming: "Sắp chiếu",
  statusShowing: "Đang chiếu",
  statusEnded: "Đã kết thúc",
  statusInactive: "Ngừng hoạt động",

  hasSchedulesError: "Không thể thực hiện thao tác vì phim đang có lịch chiếu.",

  fieldNameVn: "Tên phim (Tiếng Việt)",
  fieldNameEn: "Tên phim (Tiếng Anh)",
  fieldDirector: "Đạo diễn",
  fieldActor: "Diễn viên",
  fieldProductionCompany: "Nhà sản xuất",
  fieldDuration: "Thời lượng (phút)",
  fieldTrailer: "Trailer (URL YouTube)",
  fieldFromDate: "Ngày khởi chiếu",
  fieldToDate: "Ngày kết thúc chiếu",
  fieldContent: "Nội dung phim",
  fieldLargeImage: "Ảnh poster lớn",
  fieldSmallImage: "Ảnh poster nhỏ",
  fieldTypes: "Thể loại",
  fieldFormats: "Định dạng",
  selectAllFormats: "Chọn tất cả",

  filterStatus: "Trạng thái",
  filterFormat: "Định dạng",
  filterGenre: "Thể loại",
  filterAll: "Tất cả",
  clearFilters: "Xóa bộ lọc",
  noMovieMatchesFilter: "Không có phim nào khớp với bộ lọc.",
};

export const SCHEDULE_LABELS = {
  pageTitle: "Quản lý lịch chiếu",
  addSchedule: "Thêm suất chiếu",
  columnIndex: "STT",
  columnMovie: "Phim",
  columnRoom: "Phòng chiếu",
  columnTime: "Thời gian",
  columnPrice: "Giá vé",
  columnActions: "Thao tác",
  currencyUnit: "VND",
  fieldPriceBase: "Giá vé cơ bản (VND)",
  maxDaysAheadError: "Chỉ có thể tạo suất chiếu trong vòng 10 ngày tới.",
  roomFormatMismatchError: "Phòng chiếu không hỗ trợ định dạng đã chọn.",
  filterMovie: "Lọc theo phim",
  filterRoom: "Lọc theo phòng",
  filterAll: "Tất cả",
  labelMovie: "Phim",
  labelRoom: "Phòng",
  searchMoviePlaceholder: "Tìm theo tên phim...",
  clearFilters: "Xóa bộ lọc",
  noScheduleMatchesFilter: "Không có suất chiếu nào khớp với bộ lọc.",
  timelineRoomHeader: "Phòng",
  timelineEmpty: "Không có phòng chiếu nào.",
  columnStatus: "Trạng thái",
  statusScheduled: "Chưa chiếu",
  statusShowing: "Đang chiếu",
  statusEnded: "Đã kết thúc",
  statusCancelled: "Đã hủy",
  statusDeleted: "Đã xóa",
  detailTitle: "Chi tiết suất chiếu",
  detailEdit: "Sửa suất chiếu",
  detailClose: "Đóng",
  detailFormat: "Định dạng",
  detailDuration: "Thời lượng",
  detailRoom: "Phòng chiếu",
  detailSoldSeats: "Ghế đã bán",
  detailLoadingSeats: "Đang tải sơ đồ ghế...",
  detailSeatError: "Không thể tải sơ đồ ghế cho suất chiếu này.",
  detailMovieError: "Không thể tải thông tin phim.",
  editDeleteButton: "Xóa suất chiếu",
  editRoomLockedHint: "Không thể đổi phòng chiếu sau khi đã tạo suất chiếu.",
};

export const CONCESSION_LABELS = {
  sidebarTitle: "Quản lý bắp nước",
  pageTitle: "Quản lý bắp nước",

  tabFood: "Đồ ăn",
  tabDrink: "Nước uống",
  tabCombo: "Combo",

  itemTypeFood: "món ăn",
  itemTypeDrink: "thức uống",
  itemTypeCombo: "combo",

  columnImage: "Hình ảnh",
  columnName: "Tên",
  columnPrice: "Giá",
  columnStatus: "Trạng thái",
  columnActions: "Thao tác",

  searchPlaceholder: "Tìm kiếm...",
  addButton: "Thêm mới",
  itemLabel: "mục",
  currencyUnit: "đ",

  sizeNone: "Tiêu chuẩn",
  sizeS: "Nhỏ",
  sizeM: "Vừa",
  sizeL: "Lớn",

  statusActive: "Đang bán",
  statusInactive: "Ngừng bán",
  statusDeleted: "Đã xoá",

  actionEdit: "Chỉnh sửa",
  actionDelete: "Xoá",
  actionRestore: "Khôi phục",

  addModalTitle: "Thêm mới",
  editModalTitle: "Chỉnh sửa",

  fieldName: "Tên",
  fieldDescription: "Mô tả",
  fieldImage: "Hình ảnh",
  fieldStatus: "Trạng thái",
  fieldPrices: "Giá bán",

  namePlaceholder: "Nhập tên...",
  descriptionPlaceholder: "Nhập mô tả...",
  imagePlaceholder: "https://... hoặc tải ảnh lên",
  uploadButton: "Tải lên",
  uploadFailed: "Tải ảnh thất bại, vui lòng thử lại.",

  pricePlaceholder: "Nhập giá (tối đa 10.000.000đ)...",

  confirmDeleteTitle: "Xác nhận xoá",
  confirmDeleteMessage: "Bạn có chắc chắn muốn xoá mục này không?",

  noItemFound: "Không tìm thấy dữ liệu.",
  loadingList: "Đang tải dữ liệu...",

  createSuccess: "Thêm mới thành công.",
  updateSuccess: "Cập nhật thành công.",
  deleteSuccess: "Xoá thành công.",
  restoreSuccess: "Khôi phục thành công.",

  errorLoadList: "Không thể tải danh sách bắp nước.",
  errorSearch: "Không thể tìm kiếm bắp nước.",
  errorCreate: "Không thể thêm mới. Vui lòng kiểm tra lại thông tin.",
  errorUpdate: "Không thể cập nhật. Vui lòng kiểm tra lại thông tin.",
  errorDelete: "Không thể xoá mục này.",
  errorRestore: "Không thể khôi phục mục này.",
  nameAlreadyExists: "Tên đã tồn tại trong hệ thống.",
  foodNameAlreadyExists: "Tên món ăn đã tồn tại.",
  drinkNameAlreadyExists: "Tên thức uống đã tồn tại.",
  comboNameAlreadyExists: "Tên combo đã tồn tại.",
  foodInComboCannotDelete: "Không thể xoá món ăn đang thuộc một combo. Vui lòng xoá combo đó trước.",
  drinkInComboCannotDelete: "Không thể xoá thức uống đang thuộc một combo. Vui lòng xoá combo đó trước.",
  priceExceedsMax: "Giá bán tối đa là 10.000.000đ.",

  validationNameRequired: "Vui lòng nhập tên.",
  validationPriceRequired: "Vui lòng chọn ít nhất một loại giá.",
  validationPricePositive: "Giá bán phải lớn hơn 0.",
  validationPriceMax: "Giá bán tối đa là 10.000.000đ.",
  validationNoneExclusive: "Loại giá Tiêu chuẩn không thể kết hợp với Nhỏ/Vừa/Lớn.",

  fieldComboFoodItems: "Thành phần đồ ăn",
  fieldComboDrinkItems: "Thành phần thức uống",
  comboItemQuantityLabel: "Số lượng",
  comboNoFoodAvailable: "Chưa có món ăn khả dụng.",
  comboNoDrinkAvailable: "Chưa có thức uống khả dụng.",
  comboNoPriceAvailable: "Chưa có giá bán.",
  viewPriceButton: "Giá",
  validationComboNeedsFood: "Combo cần ít nhất 1 món ăn.",
  validationComboNeedsDrink: "Combo cần ít nhất 1 thức uống.",
  comboEmptyWarning: "Combo chưa có thành phần, cần bổ sung món ăn và thức uống.",
  comboCompositionLabel: "Thành phần",
};

export const TICKET_CHECKIN_LABELS = {
  pageTitle: "Soát vé",
  navLabel: "Soát vé",
  scanTabLabel: "Quét mã QR",
  manualTabLabel: "Nhập mã vé",
  manualInputPlaceholder: "Nhập mã vé (VD: A3K7M9P2)",
  manualSubmitButton: "Tra cứu",
  startScanButton: "Bắt đầu quét",
  stopScanButton: "Dừng quét",
  scannerPlaceholder: "Hướng camera vào mã QR trên vé",

  loading: "Đang tra cứu vé...",
  notFound: "Không tìm thấy vé với mã này.",
  genericError: "Đã xảy ra lỗi. Vui lòng thử lại.",

  ticketFound: "Thông tin vé",
  movieLabel: "Phim",
  showtimeLabel: "Suất chiếu",
  roomLabel: "Phòng chiếu",
  seatsLabel: "Ghế",
  seatCountLabel: "Số lượng vé",
  statusLabel: "Trạng thái",

  statusBooked: "Hợp lệ - Chưa soát vé",
  statusCheckedIn: "Đã soát vé",
  statusCancelled: "Đã huỷ",
  statusExpired: "Đã hết hạn",

  checkedInAtLabel: "Thời gian soát vé",
  checkedInByLabel: "Nhân viên soát vé",
  cancelledAtLabel: "Thời gian huỷ",

  confirmButton: "Xác nhận soát vé",
  confirming: "Đang xác nhận...",
  checkInSuccess: "Soát vé thành công!",
  scanAnotherButton: "Soát vé khác",

  alreadyCheckedInWarning: "Vé này đã được soát vé trước đó.",
  cancelledWarning: "Vé này đã bị huỷ, không thể soát vé.",
  expiredWarning: "Vé này đã hết hạn do suất chiếu đã kết thúc, không thể soát vé.",
};

export const BOOKING_CONCESSION_LABELS = {
  stepTitle: "Chọn bắp nước",
  stepSubtitle: "Thêm đồ ăn, thức uống hoặc combo cho suất chiếu của bạn",
  skipNote: "Bạn có thể bỏ qua bước này nếu không muốn mua thêm.",

  tabFood: "Đồ ăn",
  tabDrink: "Nước uống",
  tabCombo: "Combo",

  sizeNone: "Tiêu chuẩn",
  sizeS: "Nhỏ",
  sizeM: "Vừa",
  sizeL: "Lớn",

  quantityLabel: "Số lượng",
  currencyUnit: "đ",

  orderSummaryTitle: "Tóm tắt đơn hàng",
  seatsSubtotalLabel: "Tiền ghế",
  concessionsSubtotalLabel: "Tiền bắp nước",
  grandTotalLabel: "Tổng cộng",

  emptyList: "Hiện chưa có sản phẩm nào.",
  loadError: "Không thể tải danh sách bắp nước.",
};
